// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNUAv8wc9ujWzATpzAdgMm_bLrrIod8Og',
    appId: '1:864232946996:web:e23bc3c6c3e510ec4ab961',
    messagingSenderId: '864232946996',
    projectId: 'acthub-d24cc',
    authDomain: 'acthub-d24cc.firebaseapp.com',
    storageBucket: 'acthub-d24cc.appspot.com',
    measurementId: 'G-WYV6ZYWZ6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHDk-BYZekaSr_KVNNuMpphjd8JpbAN9U',
    appId: '1:864232946996:android:25444fba7cd48ffe4ab961',
    messagingSenderId: '864232946996',
    projectId: 'acthub-d24cc',
    storageBucket: 'acthub-d24cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9VZZSIFwxpmCn6ve6En1EK_1zXJBngj0',
    appId: '1:864232946996:ios:3d78eb95b6b4586b4ab961',
    messagingSenderId: '864232946996',
    projectId: 'acthub-d24cc',
    storageBucket: 'acthub-d24cc.appspot.com',
    iosClientId: '864232946996-aotlo7sse3b1f9ra9i9ltojk84r2lol3.apps.googleusercontent.com',
    iosBundleId: 'com.example.actHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9VZZSIFwxpmCn6ve6En1EK_1zXJBngj0',
    appId: '1:864232946996:ios:3d78eb95b6b4586b4ab961',
    messagingSenderId: '864232946996',
    projectId: 'acthub-d24cc',
    storageBucket: 'acthub-d24cc.appspot.com',
    iosClientId: '864232946996-aotlo7sse3b1f9ra9i9ltojk84r2lol3.apps.googleusercontent.com',
    iosBundleId: 'com.example.actHub',
  );
}
